### ISSUE TITLE
Uninstalling from appcenter won't close the app headless mode

### ISSUE THREAD

**Issue by LynuxDevz** [matfantinel/reminduck#15]
After updating to 1.1.0 and launching the app to check how dark mode looked on my system, I found out that it didn't changed anything, so I uninstalled the app in the hope a reinstall might help, but after uninstalling from appcenter, it looks like the app is still active in headless mode (checked in htop)

**Comment by matfantinel** [comment]
Yeah - having it run in the background makes it hard to actually close the app.
For the user, this is OK - they shouldn't have to worry if the app is running or not, as long as the reminders are shown.

However, I don't know if there's a way to capture such events like updates and/or uninstalls. I'm not sure if it's worth the effort to be honest, since they're uncommon events.

For what it's worth, simply ending the process and opening the app again (from the icon, no need to be headless) would have achieved what you wanted.

**Comment by LynuxDevz** [comment]
Sorry for opening this again. But I think I have more info on this. I believe it may help you

After updating the app to the newest version, every time I opened it (either by commandline or via the icon) resulted in a segment fault. 

Resetting schemas did not help, nor uninstalling and reinstalling. However, deleting the reminduck.db from the data folder worked!

**Comment by matfantinel** [comment]
Hmm, looks like the db had some data that the updated app wasn't able to read.

I always kept this in mind when updating and tested it multiple times, so it does sound weird.

The database model probably isn't going to change again anytime soon, though. I had to add some extra properties for the recurrent reminders update, but there's no new feature in the horizon for now.

If that happens again during normal use, please let me know!
