### ISSUE TITLE
Reminders are not deleted after uninstall

### ISSUE THREAD

**Issue by NathanBnm** [matfantinel/reminduck#29]
Reminders notifications are still sent after uninstall.

**Comment by matfantinel** [comment]
This happens because the `--headless` instance of the app is still running in the background after uninstall.  The same happens after an update, too.

I'm not entirely sure there's a way to listen to the uninstall/update event and stop/restart the app accordingly. I've noticed the AppCenter also behaves this way after its big update to 3.2.0, in which I had to manually kill the process and start it again.
