### ISSUE TITLE
🐞: Reminduck pings 53 seconds late!

### ISSUE THREAD

**Issue by joe733** [matfantinel/reminduck#54]
![Screenshot from 2020-06-05 23-58-53](https://user-images.githubusercontent.com/38415384/83910770-c1fa0400-a788-11ea-921d-66fd8e38093f.png)

The notification are persistent / sticky, won't go away unless closed.

**Comment by matfantinel** [comment]
Reminduck checks to see if a Reminder is due every 60 seconds if I'm not mistaken - which is why it took 53 seconds to display it there. It is currently accurate in minutes, not seconds :grimacing: . I'm not sure I wanna bring that time down, as I don't know a more efficient way of checking for reminders in the background.

About the persistent notification, that is intended. Reminders can be important, and once the notification goes away, it's hard to see it up in the notification center. It used to not be sticky, but after missing multiple reminders both on elementary and GNOME, I decided to make them sticky.

**Comment by joe733** [comment]
> I decided to make them sticky.

Alright.

> Reminduck checks to see if a Reminder is due every 60 seconds if I'm not mistaken, It is currently accurate in minutes, not seconds :grimacing:

Okay, so should I close this issue?

**Comment by matfantinel** [comment]
Yeah, I'll close it for you. Thanks for contributing though!
